- .gitignore
- Gemfile
- Rakefile
- doc_templates/LICENSE.md
- doc_templates/README.md.erb
- doc_templates/copyright_erb.txt
- doc_templates/copyright_js.txt
- doc_templates/copyright_ruby.txt
- ladybug-energy-model-measure.gemspec
- lib/files/schema/openapi.json
- lib/ladybug/energy_model.rb
- lib/ladybug/energy_model/extension.rb
- lib/ladybug/energy_model/model.rb
- lib/ladybug/energy_model/version.rb
- spec/files/example_face_by_face_model.json
- spec/files/example_model.json
- spec/spec_helper.rb
- spec/tests/ladybug_energy_model_measure_spec.rb
> Initialize

- lib/files/schema/openapi.json
- lib/ladybug/energy_model/aperture.rb
- lib/ladybug/energy_model/face.rb
- lib/ladybug/energy_model/model.rb
- lib/ladybug/energy_model/room.rb
- lib/ladybug/energy_model/shade.rb
- spec/files/model_multi_zone_office.json
- spec/files/model_single_zone_office.json
- spec/tests/ladybug_energy_construction_spec.rb
- Hard assigning construction for adiabatic surfaces.
- Creating ShadingSurfaceGroup at room, face and aperture level, creating separate ShadingSurfaceGroup for orphaned_shades for building. 
- Assigning adjacent surfaces at model level by looping through the surface JSONs. (TODO: setAdjacentSurface failing)
This closes #8, closes #7
> feat(bug_fixes): Construction measure

- lib/ladybug/energy_model/model.rb
- lib/ladybug/energy_model/room.rb
I also fixed some of the indentation in the Rooms to make the code more readable.
> fix(model): Assign the north and the terrain from the Model object

- lib/files/model.json
- lib/from_honeybee.rb
- lib/from_honeybee/construction/air_wall.rb
- lib/from_honeybee/construction_set.rb
- lib/from_honeybee/hvac/ideal_air.rb
- lib/from_honeybee/material/window_blind.rb
- lib/from_honeybee/material/window_shade.rb
- lib/from_honeybee/model.rb
- lib/from_honeybee/schedule/fixed_interval.rb
- spec/files/LabBuilding.json
- spec/files/detailed_ideal_air.json
- spec/files/detailed_simulation_par.json
- spec/files/model_multi_zone_office.json
- spec/files/model_single_zone_office.json
- spec/files/model_single_zone_office_detailed_loads.json
- spec/files/model_single_zone_office_fixed_interval.json
- spec/files/model_with_humidity_setpoints.json
- spec/files/schedule_fixedinterval_increasing_single_day.json
- spec/tests/ladybug_energy_construction_spec.rb
- spec/tests/ladybug_energy_spacetype_spec.rb
- Fixes errors on running bundle exec rake
> fix(issues): Work through errors and issues  

- lib/from_honeybee/geometry/face.rb
- lib/from_honeybee/hvac/ideal_air.rb
- lib/from_honeybee/load/people.rb
- lib/from_honeybee/schedule/type_limit.rb
This commit brings the measure in line with this recent change in the schema:
https://github.com/ladybug-tools/honeybee-schema/pull/44
> fix(autocalculate): Update based on recent schema change

- lib/from_honeybee/geometry/face.rb
- lib/from_honeybee/geometry/room.rb
I'm guessing that the tests weren't re-run after the last PR.  This is why we really need to get continuous integration set up since I know it's not realistic to trust ourselves that we'll always run the tests locally.
> fix(face): Fix bug in previous PR

- .releaserc.json
- .travis.yml
This should trigger travis to run an automated release to github each time that we merge a PR into master. The version will be automatically incremented according to semantic release and the names of our commit messages.
> feat(ci): Automate the versioning

- README.md
This will also give me a chance to test whether the auto-deployment is correct.
> feat(docs): Add link to tests to README

- LICENSE.md
- README.md
- lib/from_honeybee.rb
- lib/from_honeybee/schedule/type_limit.rb
- lib/measures/from_honeybee_model/measure.rb
- lib/measures/from_honeybee_model/tests/from_honeybee_model_test.rb
- lib/measures/from_honeybee_simulation_parameter/measure.rb
- lib/measures/from_honeybee_simulation_parameter/tests/from_honeybee_simulation_parameter_test.rb
- spec/tests/honeybee_construction_set_spec.rb
- spec/tests/honeybee_hvac_spec.rb
- spec/tests/honeybee_material_spec.rb
- spec/tests/honeybee_schedule_spec.rb
And also adding documentation to the ReadMe so that I don't forget to do it in the future.
> docs(copyright): Update copyright using doc_templates

- lib/from_honeybee/_openapi/model.json
- lib/from_honeybee/_openapi/simulation-parameter.json
- spec/samples/model/model_5vertex_sub_faces_interior.json
- spec/tests/honeybee_model_spec.rb
We have changed at least one of the defaults on the honeybee-schema end so I am pushing an update here.
I am also adding a sample of interior apertures to be triangulated for @macumber .
> fix(openapi): Update the OpenAPI specification

- README.md
- lib/from_honeybee/model.rb
I'm also updating the links in the readme
> fix(model): Set standards type so it can run with standards measures

- README.md
- lib/from_honeybee/_openapi/model.json
- lib/from_honeybee/_openapi/simulation-parameter.json
- lib/from_honeybee/simulation/parameter.rb
- spec/samples/simulation_parameter/simulation_par_detailed.json
- spec/samples/simulation_parameter/simulation_par_simple.json
- spec/tests/honeybee_simulation_parameter_spec.rb
This commit ensures that the updated ShadowCalculation that works with E+ 9.3 is translated correctly.
I also updated the honeybee-schema OpenAPI specification based on the most recent version of honeybee-schema.
> fix(openstudio): Ensure ShadowCalculation is translated correctly

- lib/from_honeybee/schedule/ruleset.rb
Resolves https://github.com/ladybug-tools/honeybee-openstudio-gem/issues/118
> fix(schedule): Ensure ScheduleTypeLimits are assigned to ScheduleDays

- .github/workflows/emit-release-event.yaml
fix #126
Related to ladybug-tools/lbt-grasshopper#123
> ci(actions): send repo dispatch event too lbt-grasshopper on release

- lib/from_honeybee/construction/air.rb
- lib/from_honeybee/schedule/ruleset.rb
- lib/from_honeybee/simulation/parameter.rb
- spec/tests/honeybee_simulation_parameter_spec.rb
I am also implementing a workaround for a bug with air walls in the AirFlowNetwork.
> fix(holida): Ensure Holidays are added to the OpenStudio Model

- lib/from_honeybee/ventcool/control.rb
Resolves https://github.com/ladybug-tools/honeybee-openstudio-gem/issues/142
> fix(ventcool): Integrate schedule values into AFN EMS control

- lib/from_honeybee/geometry/room.rb
Resolves https://github.com/ladybug-tools/honeybee-openstudio-gem/issues/144
> fix(room): Ensure Room load definitions override space type

- lib/from_honeybee/geometry/room.rb
More info on the bug can be found here:
https://discourse.ladybug.tools/t/export-to-open-studio/11971/5
> fix(room): Handle the case of no program assigned to a room

- lib/measures/from_honeybee_model/measure.rb
- lib/measures/from_honeybee_simulation_parameter/measure.rb
- lib/to_openstudio/schedule/ruleset.rb
This commit officially released the refactored version of the gem now that it has been tested with the plugin.
I am also including a fix for ScheduleRuleSet, which avoids the case of ID collisions with the default IDF names that OpenStudio assigns.
> feat(refactor): Release refactored version with OSM import capability

- lib/to_openstudio/hvac/Model.hvac.rb
More information can be found here:
https://github.com/NREL/openstudio-standards/issues/969
> fix(hvac): Fix issue with DOAS HVAC templates

- lib/to_openstudio/model.rb
> fix(model): Fix typo with humidistat

- lib/honeybee/_defaults/model.json
- lib/honeybee/_defaults/simulation-parameter.json
- lib/to_openstudio/hvac/Model.hvac.rb
- lib/to_openstudio/hvac/template.rb
- spec/samples/hvac/fcu_with_doas_template.json
- spec/samples/hvac/vav_template.json
- spec/samples/hvac/window_ac_with_baseboard_template.json
- spec/samples/model/model_energy_allair_hvac.hbjson
- spec/samples/model/model_energy_doas_hvac.hbjson
- spec/samples/model/model_energy_window_ac.hbjson
See here for more info:
https://github.com/ladybug-tools/honeybee-schema/pull/245
> fix(hvac): Change the convention used to identify HVAC templates

- lib/to_openstudio/hvac/template.rb
It seems that the standards gem doesn't include any ventilation for all PTACs, which makes the comparison with DOAS systems uneven. This should fix the issue.
> fix(hvac): Ensure ventilation happens for PTAC systems

- lib/from_openstudio/material/window_blind.rb
- lib/from_openstudio/material/window_glazing.rb
- lib/from_openstudio/model.rb
- spec/samples/osm_material/winMatBlind.osm
- spec/samples/osm_material/winMatGlaz.osm
- spec/tests/osm_material_spec.rb
- Adds translators for window blind, window glazing.
- Remaining material translators - window gas, window gas mixture, window gas custom
> feat(material): Adds reverse translators for windows

- lib/from_openstudio/material/window_gas.rb
- lib/from_openstudio/material/window_gas_custom.rb
- lib/from_openstudio/material/window_gas_mixture.rb
- lib/from_openstudio/model.rb
- spec/samples/osm_material/winMatGas.osm
- spec/samples/osm_material/winMatGasCustom.osm
- spec/samples/osm_material/winMatGasMixture.osm
- spec/tests/osm_material_spec.rb
Adds reverse translator and tests for window gas, window gas mixture, window gas custom.
> feat(material): Adds reverse translators for window gas materials

- lib/honeybee/_defaults/model.json
- lib/honeybee/hvac/template.rb
- lib/to_openstudio/hvac/template.rb
- spec/samples/hvac/fcu_with_doas_template.json
- spec/samples/model/model_energy_doas_hvac.hbjson
I am also taking the opportunity to clean up several aspects of the template HVAC systems now that I understand them better.
> fix(hvac): Add option for demand controlled ventilation

- .github/workflows/ci.yaml
- Gemfile
- honeybee-openstudio.gemspec
- lib/to_openstudio/construction/air.rb
- lib/to_openstudio/schedule/fixed_interval.rb
- spec/samples/osm_material/winMatGasMixture.osm
There's not too much to change here.  Just a couple of properties and an update to the CI.
> feat(openstudio): Upgrade to OpenStudio version 3.2

- README.md
I forgot to squash and merge Dan's last PR so that it gets a release tag.
> fix(release): Trigger release with new bug fix

- README.md
This commit is also triggering a release so that we can test the new CI.
> fix(readme): Use correct and updated tags

- .github/workflows/ci.yaml
- lib/honeybee/model_object.rb
Somehow the regex was not removing { and }. I have tested it and it works now.
> fix(clean_identifier): Fix bug in clean_identifier method

- lib/from_openstudio/construction/air.rb
- lib/from_openstudio/construction/opaque.rb
- lib/from_openstudio/construction/shade.rb
- lib/from_openstudio/construction/window.rb
- lib/from_openstudio/construction_set.rb
- lib/from_openstudio/geometry/aperture.rb
- lib/from_openstudio/geometry/door.rb
- lib/from_openstudio/geometry/face.rb
- lib/from_openstudio/geometry/room.rb
- lib/from_openstudio/geometry/shade.rb
- lib/from_openstudio/material/opaque.rb
- lib/from_openstudio/material/opaque_no_mass.rb
- lib/from_openstudio/material/window_blind.rb
- lib/from_openstudio/material/window_gas.rb
- lib/from_openstudio/material/window_gas_custom.rb
- lib/from_openstudio/material/window_gas_mixture.rb
- lib/from_openstudio/material/window_glazing.rb
- lib/from_openstudio/material/window_simpleglazsys.rb
- lib/honeybee/model_object.rb
This should be better than just removing the characters and I am also making sure that all materials and constructions get their characters escaped.
> fix(from_openstudio): Ensure that all non-ascii characters are escaped

- lib/from_openstudio/model.rb
- lib/from_openstudio/schedule/ruleset.rb
- lib/from_openstudio/schedule/type_limit.rb
- spec/tests/osm_schedules_spec.rb
This is a follow-up PR from this one:
https://github.com/ladybug-tools/honeybee-openstudio-gem/pull/226
> fix(schedule): Implement a few small corrections to Schedules

- lib/to_openstudio/geometry/face.rb
- lib/to_openstudio/geometry/shade.rb
We are just going to have the core libraries pass the vertices in the correct order when we  have a Face or Shade with holes.
> fix(geometry): Add code to handle geometry with holes

- lib/from_openstudio/model.rb
I realize @tanushree04 has a better solution for this in her PR but it may be a few more days before this is merged so I'm just going to patch it quickly now.
> fix(schedule): Ensure FixedInterval schedule doesn't overwrite Ruleset

- lib/from_openstudio.rb
- lib/from_openstudio/geometry/door.rb
- lib/from_openstudio/geometry/face.rb
- lib/from_openstudio/geometry/room.rb
- lib/from_openstudio/geometry/shade.rb
- lib/from_openstudio/material/vegetation.rb
- lib/from_openstudio/model.rb
- lib/honeybee.rb
- lib/honeybee/_defaults/model.json
- lib/honeybee/material/vegetation.rb
- lib/to_openstudio.rb
- lib/to_openstudio/construction/dynamic.rb
- lib/to_openstudio/material/vegetation.rb
- lib/to_openstudio/model.rb
- lib/to_openstudio/ventcool/opening.rb
I am also making sure that the geometry object display names are transferred to the HBJSON upon import.
> feat(material): Add roof vegetation material

- lib/to_openstudio/load/service_hot_water.rb
I realized that the WaterHEater object is more versatile than I originally gave it credit for. So I'm changing all of the SHW system templates to use that.
> fix(shw): Implement better ways of modeling SHW with WaterHeater

- lib/to_openstudio/hvac/template.rb
- lib/to_openstudio/model.rb
See here for more information:
https://discourse.ladybug.tools/t/bug-all-air-hvac-economizer-type-assignment-to-multiple-zones/17657/2
> fix(hvac): Ensure that PSZ systems get properties applied to all loops

- lib/to_openstudio/simulation/parameter_model.rb
It seems there are a lot of measures that need the climate zone so I might as well assign it.
> fix(simulation): Add method to assign climate zone if unspecified

- lib/from_openstudio/geometry/room.rb
- lib/from_openstudio/hvac/ideal_air.rb
- lib/from_openstudio/model.rb
> feat(hvac): Add ideal air system

- lib/to_openstudio/hvac/template.rb
At the very least, this will make the results from chillers and boilers a lot more reasonable. We essentially call the methods that underlie the model_apply_hvac_efficiency_standard method in the standards gem but with typical sizes for the various pieces of equipment.
> fix(hvac): Use reasonable efficiency defaults when lacking a sizing run

- lib/from_openstudio/hvac/ideal_air.rb
- spec/tests/osm_ideal_system_spec.rb
- spec/tests/osm_material_spec.rb
Adds Tests for translation of Ideal Air System OS object to HBJSON object
> Feat(hvac): Add test for Ideal Air System OS object translation

- .github/workflows/ci.yaml
- lib/to_openstudio/simulation/parameter_model.rb
I forgot that our .NET bindings are using a 0 integer in place of a null.
> fix(simulation): Handle optional enumerations from the .NET side

- Gemfile
- honeybee-openstudio.gemspec
- lib/files/urbanopt_Gemfile
- lib/to_openstudio/model.rb
This commit also includes an enhancement of setting the Building name in the OSM using the Model name/identifier.
> fix(urbanopt): Specify fixed versions for all URBANopt dependencies

- .github/workflows/ci.yaml
- .releaserc.json
- lib/to_openstudio/ventcool/fan.rb
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/1012
> fix(fan): Fix typo in fan ventilation schedule

- lib/to_openstudio/hvac/Model.hvac.rb
- lib/to_openstudio/hvac/template.rb
Resolves https://github.com/ladybug-tools/honeybee-openstudio-gem/issues/329
> fix(hvac): Use variable fans when modeling DOAS with DCV
