ladybug-tools/honeybee-openstudio-gem

lib/ladybug/energy_model/aperture.rb, lib/ladybug/energy_model/door.rb, lib/ladybug/energy_model/face.rb, lib/ladybug/energy_model/room.rb, lib/ladybug/energy_model/shade.rb
This fixes the issue of Space-assigned shades here (https://github.com/ladybug-tools-in2/energy-model-measure/issues/29). It's admittedly not as elegant or efficient as I would like it to be given that I couldn't pass the parent Space of a Surface to the to_openstudio method that creates the Surface. So we have a particularly large Room class now and we might want to consider changing this down the line as I mentioned here (https://github.com/ladybug-tools-in2/energy-model-measure/issues/33).
This commit also reorganizes a lot of the code on the 5 geometry objects and added some more comments so that it is clear what is happening in each section.
Lastly, I fixed a bug in the shade transmittance_schedule, which was not correctly implemented.
=> fix(shade): Assign all Shade within the Room class to use setSpace()

lib/ladybug/energy_model/construction_set.rb, lib/ladybug/energy_model/face.rb, lib/ladybug/energy_model/room.rb
This commit fixes this issue (https://github.com/ladybug-tools-in2/energy-model-measure/issues/34).
The code is a bit longer than I would have hoped since it seems the OpenStudio SDK provides no method to lookup a default construction based on surface type and boundary condition (I need to have a complete surface with the properties in order to look it up). But the solution now works and it's clean so I can't complain much.
I also cleaned up some lines of code that were really long and I had to scroll to see. And I reduced the number of lines of code in the construction set class to make it more concise/elegant.
=> fix(adiabatic): Fix assigning of constructions to adiabatic surfaces

lib/files/model.json, lib/ladybug/energy_model/ideal_air_system.rb, lib/ladybug/energy_model/model.rb, lib/ladybug/energy_model/room.rb, lib/ladybug/energy_model/space_type.rb
This commit overhauls how HVAC systems are represented in the schema.
Specifically, it makes it possible in the future to support HVAC systems that are assigned to multiple Rooms (like most of the HVAC system templates in honeybee_legacy). It also restructures the representation of HVAC within the Model schema in order to support this.
This commit is coordinated with [this PR over on honeybee_energy](https://github.com/ladybug-tools/honeybee-energy/pull/69) and [this PR in honeybee_shcema](https://github.com/ladybug-tools-in2/honeybee-schema/pull/12)
=> feat(hvac): Refactor HVAC to be extensible for future systems

lib/from_honeybee/model.rb, lib/from_honeybee/simulation/designday.rb, lib/from_honeybee/simulation/parameter.rb
The SimulationParameter class was getting pretty long and the DesignDay is a pretty self-contained unit so I pulled it out into its own class.
=> refactor(designday): Pull DesignDay creation out into its own class

lib/from_honeybee/geometry/face.rb, lib/from_honeybee/geometry/room.rb
We recently decided that it was weird that people could not assign shades to Doors but they could to all other geometry objects as noted by [this change in the schema](https://github.com/ladybug-tools-in2/honeybee-schema/pull/24).  This commit updates the measure to support this new feature and I also put the code that creates shade groups into a function so that we have less copy/pasted code.
=> feat(door): Allow Shades to be assigned to Doors

lib/from_honeybee/geometry/room.rb, spec/tests/honeybee_model_spec.rb
This commit enables the energy-model-measure to use the story properties recently added to the Room schema.  It also adds rooms to a dummy story if no stories are specified.
This way, David's measures should always work with the Model output from this measure.
=> feat(room): Add story property to Room

lib/files/Honeybee.rb, lib/files/urbanopt_Gemfile
It seems like this is the last thing that is needed to bypass the `uo -p` command and generate all of the files needed for an urbanopt simulation ourselves.
However, including this gemfile means that we will have to update it whenever we want to upgrade to a new version of URBANopt.
I also simplified some of the code in the mapper and improved the docstrings.
=> feat(urbanopt): Add gemfile for URBANopt

README.md, honeybee-openstudio.gemspec, lib/files/urbanopt_Gemfile
It seems like energy-model-measure has become a misnomer at this point since the package is currently a lot more than a measure.  It's at least 2 measures (from_honeybee_model and from_honeybee_simulation_parameter) as well as a whole library of translators that are used by the measures but can also be run independently of these measures. 
So this commit changes the name of the this repo to honeybee-openstudio-gem and makes the official name of the Ruby gem honeybee-openstudio.
=> feat(name): Change gem name to honeybee-openstudio

.travis.yml
The deploy job has a script that replaces the gemspec version by the new tag ($TRAVIS_TAG)
close #112
=> ci(semantic-release): replace gemspec version on release

.travis.yml, Gemfile, README.md, honeybee-openstudio.gemspec, lib/from_honeybee/schedule/ruleset.rb, lib/from_honeybee/simulation/parameter.rb, spec/tests/honeybee_simulation_parameter_spec.rb
BREAKING CHANGE: This commit officially upgrades the honeybee-openstudio-gem to work with OpenStudio 3.0. It also upgrades the version of the openstudio-extension-gem that we use to 0.2.3 among other dependencies.
The few OpenStudio SDK methods that have changed in OpenStudio 3.0 have been updated but the measure still techanically can run with OpenStudio 2.9.1 thanks to some `begin/rescue` statements.  I have marked all of these statements with a `# REMOVE:` comment so that we can go back later and delete them, thereby keeping the code clean.
Resolves https://github.com/ladybug-tools/honeybee-openstudio-gem/issues/98
Resolves https://github.com/ladybug-tools/honeybee-openstudio-gem/issues/15
@tanushree04 ,
I just requested your review here so that you are aware of the change. This …
=> feat(openstudio): Upgrade to OpenStudio 3.0

lib/from_honeybee.rb, lib/from_honeybee/_openapi/model.json, lib/from_honeybee/construction/window.rb, lib/from_honeybee/construction/windowshade.rb, lib/from_honeybee/model.rb, spec/samples/construction/construction_window_shade.json, spec/tests/honeybee_construction_spec.rb
This PR is coordinated with [this one over on honeybee-energy](https://github.com/ladybug-tools/honeybee-energy/pull/211).
It fixes the way that blinds and shades were represented in the schema previously, which could never be simulated by EnergyPlus since E+ always needs a ShadingControl object in order to be able to simulate them. So I added a new WindowConstructionShaded class to handle the creation of this ShadingControl object and allow users to change some of its properties.
Resolves https://github.com/ladybug-tools/honeybee-openstudio-gem/issues/90
=> feat(construction): Add WindowConstructionShade

lib/from_honeybee/_defaults/model.json, lib/from_honeybee/_defaults/simulation-parameter.json, lib/from_honeybee/hvac/Model.hvac.rb, lib/from_honeybee/hvac/ideal_air.rb, lib/from_honeybee/hvac/template.rb, lib/from_honeybee/model.rb, lib/from_honeybee/schedule/type_limit.rb, spec/samples/hvac/fcu_with_doas_template.json, spec/samples/hvac/vav_template.json, spec/samples/hvac/window_ac_with_baseboard_template.json, spec/samples/model/model_energy_allair_hvac.json, spec/samples/model/model_energy_doas_hvac.json, spec/samples/model/model_energy_window_ac.json, spec/tests/honeybee_hvac_spec.rb, spec/tests/honeybee_model_spec.rb
Since all of the heavy lifting is done by the standards gem, this commit really only required one new hvac/template module.  I also copy/pasted the Model.hvac.rb that is distributed with the "Create Typical Building" measure, which I have reason to beleive may eventually be included within the standards gem.
This commit also updates the openapi specification and fixes a few bugs I discovered with the ideal air system.
=> feat(hvac): Add modules to add standards gem HVAC templates

lib/from_honeybee/_defaults/model.json, lib/from_honeybee/ventcool/opening.rb, spec/samples/model/model_energy_window_ventilation.json, spec/samples/ventcool/ventilation_opening_default.json
If we want to use the discharge coefficient in both simple ventilation and the AFN, it seems we should follow the E+ guide and use a coefficient that corresponds to the height from midpoint of lower opening to the neutral pressure level (deltaHnpl) instead of using the full height of the window.
=> fix(ventcool): Set default discharge coefficient to 0.45 for deltaHnpl

lib/from_honeybee/_defaults/model.json, lib/from_honeybee/geometry/face.rb, lib/from_honeybee/geometry/room.rb, lib/from_honeybee/model.rb, lib/from_honeybee/program_type.rb, lib/from_honeybee/ventcool/control.rb, lib/from_honeybee/ventcool/opening.rb, lib/from_honeybee/ventcool/simulation.rb, spec/samples/model/model_energy_afn.json, spec/samples/ventcool/ventilation_crack.json, spec/samples/ventcool/ventilation_simulation_control.json, spec/tests/honeybee_model_spec.rb, spec/tests/honeybee_ventcool_spec.rb
This commit adds methods and classes to translate the AFN from honeybee-schema.
The global trigger to initialize the use of the AFN lies in the VentilationSimulationControl, which is processed first before the rest of the model is translated.  If the simulation control calls for anything other than "SingleZone", none of the simple zone ventilation, infiltration, or air mixing objects are added to the model.  Instead, the AFN is set up with the vent_crack objects on each Face being translated and any VentilationOpening objects are converted to AFN SimpleOpening objects.  Lastly, the VentilationControl objects assigned to each Room are translated to an EMS program instead of the usual WindAndStack object.
The gem is smart enough to recognize when adjacent surfaces already have their crack …
=> feat(afn): Add methods and classes to translate honeybee_schema AFN

lib/from_honeybee/geometry/room.rb, lib/from_honeybee/ventcool/control.rb, lib/from_honeybee/ventcool/opening.rb
We allow people to assign VentilationOpening objects to interior windows to control their properties for AFN simulation but we need to make sure that these are ignored during single zone simulation.
I'm also making sure that the EMS variables are completely free of special characters and are also unique.
=> fix(ventcool): Ensure only outdoor windows are used in simple vent

lib/from_honeybee/model.rb
With this change, it will be possible to assign the same ideal air system to several rooms and the gem will take care of the necessary duplication for EnergyPlus.  It also enforces a strict naming convention for all ideal air systems such that we will always be able to match results back to the Honeybee Model.
=> fix(hvac): Enforce strict naming of Ideal Air Systems

lib/files/urbanopt_Gemfile
All of the features currently in the gem are compatible with the latest URBANopt so I'm updating it.
=> fix(urbanopt): Update version of the gem used by URBANopt

lib/from_honeybee/model.rb
Schedules must be translated before constructions since there are a couple of construction types that use schedules but the reverse is never true.
=> fix(model): Ensure schedules are available for constructions

.github/workflows/ci.yaml, lib/to_openstudio/construction/air.rb, lib/to_openstudio/hvac/template.rb, lib/to_openstudio/schedule/ruleset.rb, lib/to_openstudio/simulation/parameter_model.rb
The changes here include the cleaning up of "bridge" code that was just to run the measure in OpenStudio 2.9.1 (back when we were first developing it).
Now that the E+ AFN can work with the ConstructionAirBoundary, I also removed the hack to get it to work (with IR transparent surface).
Resolves https://github.com/ladybug-tools/honeybee-openstudio-gem/issues/117
=> feat(openstudio): Upgrade for compatibility with OpenStudio 3.1.0

lib/files/honeybee_adapter.rb
By specifying the path to this file in the OSW, we will be able to see the E+ simulation progress whenever we run reporting measures.
CC: @macumber ; Just letting you know that I'm officially incorporating this into the plugin and core libraries
=> feat(adapter): Add adapter to view simulation progress with measures

lib/to_openstudio/model.rb
For the other HVAC templates, we'll probably have to add extra pieces of equipment in order to be able to account for humidification. But this at least ensures expected behavior for the Ideal Air template.
=> fix(hvac): Ensure humidistat is used with Ideal Air if specified

lib/honeybee/model_object.rb, lib/to_openstudio/hvac/template.rb
It seems that the order of objects returned by the OpenStudio getXXX method is not consistent. This fix ensures that we pull the air loop from the zones instead of this method.
I am also adding a small fix to the method that cleans the IDs of geometry so that they are safe for Radiance.
Resolves https://github.com/ladybug-tools/honeybee-openstudio-gem/issues/192
Resolves https://github.com/ladybug-tools/honeybee-openstudio-gem/issues/180
=> fix(hvac): Ensure that the correct air loop is pulled

lib/honeybee/_defaults/energy_default.json, lib/honeybee/_defaults/model.json, lib/to_openstudio/construction/opaque.rb, lib/to_openstudio/construction/window.rb, lib/to_openstudio/construction/windowshade.rb, spec/samples/construction/construction_opaque_door.json, spec/samples/construction/construction_opaque_roof.json, spec/samples/construction/construction_opaque_wall.json, spec/samples/construction/construction_window_blinds.json, spec/samples/construction/construction_window_double.json, spec/samples/construction/construction_window_shade.json, spec/samples/construction/construction_window_triple.json, spec/samples/construction_set/constructionset_complete.json, spec/samples/construction_set/constructionset_partial_exterior.json, spec/samples/model/model_complete_multi_zone_office.hbjson, spec/samples/model/model_complete_single_zone_office.hbjson, spec/samples/model/model_energy_no_program.hbjson, spec/samples/model/model_energy_shoe_box.hbjson, spec/samples/model_large/lab_building.hbjson, spec/samples/model_large/single_family_home.hbjson, spec/tests/honeybee_construction_spec.rb
I have come around to realizing that the OpaqueConstruction and WindowConstruction should use the key "materials" instead of "layers" in order to be consistent between abridged and non-abridged schemas.
I am changing the forward translator to accept both the old and new schema.
@tanushree , this will affect the reverse translator that you are currently working on since you should translate the constructions to the new schema (with the "materials" key instead of the "layers" key).
=> fix(construction): Change construction schema to be more consistent

lib/from_openstudio/model.rb, lib/measures/from_honeybee_model_to_gbxml/measure.rb
This includes the removal of the "dummy space" on import that you need to put into gbXML in order to have context shade. It also includes making sure that the zone name is always different than the space name.
=> fix(gbxml): Add extra checks to comply with gbXML

lib/measures/from_honeybee_model/measure.rb, lib/to_openstudio/model.rb
OS Workflow is hard coded to look in generated files dir first
=> Copy exported schedules to generated files dir,

lib/from_openstudio/geometry/aperture.rb, lib/from_openstudio/geometry/door.rb, lib/from_openstudio/geometry/face.rb, lib/from_openstudio/geometry/shade.rb, lib/from_openstudio/model.rb
I realized that the format of window constructions within gbXML doesn't support material layers and so the current setup of the gem meant that almost no gbXMLs were importable back to honeybee. I added in some checks to ensure that, if a construction is not found, we don't assign it to any faces. This keeps the output HBJSON valid and ensures that these objects with missing constructions just get the honeybee default.
=> fix(construction): Ensure output is valid with missing constructions

lib/from_openstudio/material/window_glazing.rb
It seems that, if we don't .get the value, it gets written into the JSON as a string.
=> fix(glazing): Ensure that the numerical value is obtained

lib/to_openstudio/geometry/face.rb, lib/to_openstudio/geometry/room.rb, lib/to_openstudio/ventcool/opening.rb
This commit ensures that horizontal apertures can be simulated with the AFN. There currently aren't any checks to ensure that horizontal exterior apertures are-inoperable but these are better addressed on the UI end.
=> fix(afn): Handle the case of horizontal Apertures

lib/honeybee/_defaults/energy_default.json, lib/honeybee/model.rb, lib/measures/from_honeybee_model_to_gbxml/measure.rb, lib/to_openstudio/construction/window.rb, lib/to_openstudio/geometry/room.rb
This commit ensures that properties like honeybee-calculated room volume make it into the IDF. It also ensures that properties like U-value and SHGC make it into the gbXML.
=> fix(model): Ensure autocalculated properties make it to IDF and gbXML

lib/from_openstudio/schedule/type_limit.rb, lib/honeybee/model_object.rb, spec/samples/idf/5ZoneAirCooled.idf, spec/samples/osm_schedule/scheduleRuleset.osm, spec/tests/idf_to_honeybee_spec.rb, spec/tests/osm_schedules_spec.rb
It seems that one of the arguments I was using for encoding ASCII is deprecated. Also, it seems that there's an old default in the OpenStudio SDK in regard to the ControlMode unit type. This can catch and fix this case.
=> fix(style): Remove deprecated args and incorrect default

lib/to_openstudio/construction/dynamic.rb, lib/to_openstudio/ventcool/control.rb
It seems that some people will give IDs to objects that contain no valid EMS characters and we should be prepared to handle these cases.
=> fix(ems): Ensure that correct EMS variables are always used

lib/to_openstudio/geometry/aperture.rb, lib/to_openstudio/geometry/door.rb, lib/to_openstudio/geometry/face.rb, lib/to_openstudio/geometry/shade.rb
After delving a little into the OpenStudio source code, I have realized that the methods we have in ladybug_geometry to obtain the upper-left vertex are a bit better than OpenStudio's. This is particularly so in cases where we have to decide whether the "upper" or the "left" is of a higher importance for a given geometry.
So I now just ensure that the HBJSON that the gem gets will always have vertices fed to it in a manner that is upper-left -counter-clockwise using our methods in ladybug_geometry. And I am removing the methods here that would replace these vertices with a potentially less-accurate version.
=> fix(geometry): Remove the automatic reorderULC for all vertices

lib/to_openstudio/hvac/template.rb
It seems that the standards gem is pretty smart and it will not add zones to the DOAS if they have no outdoor air ventilation requirement. So we have to loop through the zones assigned to a HVAC system until we find one that is connected to the air loop.
=> fix(template): Ensure we find a zone that's connected to the air loop

lib/from_openstudio.rb, lib/from_openstudio/geometry/room.rb, lib/from_openstudio/load/service_hot_water.rb, spec/tests/osm_to_honeybee_spec.rb
Fixes #264 
- Adds reverse translator for Service Hot Water
- At the room level, creates new reverse translator object if OS Water Use Equipment object is present
=> feat(ServiceHotWater): Adds Service Hot water reverse translator

lib/honeybee/model.rb, lib/to_openstudio/geometry/aperture.rb, lib/to_openstudio/geometry/door.rb, spec/tests/honeybee_model_spec.rb
It seems there are some times when we really want to turn this off (gbXML export in particular). So I'm exposing it as a global variable, which we might expose as an option on certain measures.
=> fix(aperture): Expose sub-face triangulation as a global option

.github/workflows/ci.yaml, Gemfile, honeybee-openstudio.gemspec, lib/honeybee/extension.rb, lib/honeybee/model.rb, lib/honeybee/model_object.rb, lib/honeybee/simulation/parameter_model.rb, lib/measures/from_honeybee_simulation_parameter/measure.rb, lib/to_openstudio/hvac/radiant.rb, spec/tests/gbxml_to_honeybee_spec.rb, spec/tests/honeybee_model_spec.rb, spec/tests/honeybee_simulation_parameter_spec.rb, spec/tests/idf_to_honeybee_spec.rb, spec/tests/osm_to_honeybee_spec.rb
It seems that something has become weird with the JSON schema dependency so I am just removing the validation functions from the gem. We've only been using them in tests, anyway, and they are not used at all in the translation functions of the gem.
=> fix(model): Update gem for OpenStudio 3.5

lib/honeybee.rb, lib/honeybee/_defaults/model.json, lib/honeybee/geometry/shademesh.rb, lib/honeybee/model_object.rb, lib/to_openstudio.rb, lib/to_openstudio/geometry/face.rb, lib/to_openstudio/geometry/room.rb, lib/to_openstudio/geometry/shademesh.rb, lib/to_openstudio/model.rb
I tested this in a few situations and verified that it results in much better fidelity to what the user expects. Now, all of the solar calculations won't be incorrect because EnergyPlus is trying to fix things and makes them worse.
=> fix(face): Overwrite Face Type to avoid E+ auto-flipping geometry

lib/to_openstudio/simulation/parameter_model.rb
It seems that, even when you tell the OSM to not perform the sizing calculation with simulation control, the OpenStudio SDK does not translate this into the IDF. To get around this, I'm taking an iron-fisted approach where I just don't write the design days into the OSM/IDF when simulation control says to not perform zone sizing.
This produces the desired behavior, though I should note that the simulation is only successful when the model is unconditioned or the only HVAC is IdealAir with NoLimit sizing and no exonomizer.
=> fix(simulation): Take an iron-fisted approach with Simulation Control
